# Generated by Django 5.0.4 on 2024-05-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_contact_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('order_name', models.EmailField(max_length=50)),
                ('phone', models.IntegerField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
    ]
